// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NbSites.Web.Data;

#nullable disable

namespace NbSites.Web.Migrations
{
    [DbContext(typeof(DemoDbContext))]
    [Migration("20230328073637_EmptyDb")]
    partial class EmptyDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.15");
#pragma warning restore 612, 618
        }
    }
}
